AllCops:
  Exclude:
    - "gemfiles/**/*"
    - "vendor/**/*"
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
